version: '3.7'

services:
  redis:
    image: redis:7
    command: redis-server --appendonly yes --requirepass whisper
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=whisper
    volumes:
      - redis:/data
  s3:
    restart: unless-stopped
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    ports:
      - '9000:9000'
      - '9001:9001'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: whisper123
      MINIO_ROOT_PASSWORD: whisper123
    volumes:
      - minio:/data

  sqs:
    restart: unless-stopped
    image: softwaremill/elasticmq-native:1.3.14
    ports:
      - '9324:9324'
      - '9325:9325'
    volumes:
      - './sqs.conf:/opt/elasticmq.conf'
      - 'elasticmq:/data'

volumes:
  redis:
  minio:
  elasticmq:
